### ISSUE TITLE
Splitting crashes the server

### ISSUE THREAD

**Issue by Maxetto** [OgarProject/Ogar#160]
As in Title, the new splitting method crashes the server.
Running on Debian 7.2.0, latest Ogar commit as https://github.com/OgarProject/Ogar/commit/e896f9f2a4f6bb45adad1a5ce746fb9b5a3209e2

EDIT: Log
>TypeError: Cannot read property '651' of undefined
    at GameServer.splitCells (/root/ogar/src/GameServer.js:584:51)
    at Mode.pressSpace (/root/ogar/src/gamemodes/Mode.js:52:16)
    at PlayerTracker.update (/root/ogar/src/PlayerTracker.js:83:34)
    at GameServer.updateClients (/root/ogar/src/GameServer.js:419:39)
    at GameServer.mainLoop (/root/ogar/src/GameServer.js:389:14)
    at wrapper [as _onTimeout] (timers.js:274:14)
    at Timer.listOnTimeout (timers.js:119:15)

**Comment by Ephemerality** [comment]
My bad. Fixed in 625e842b11f265f81c3acde19c35f3bfbb028ad4.

**Comment by Maxetto** [comment]
Thank you, perfectly working now ;)

**Comment by amazingty** [comment]
i got it in windows and it still crashes my friend pls help ?

**Comment by JCookie20001** [comment]
Try re-installing ogar.


________________________________

**Comment by amazingty** [comment]
Already done that didnt fix the problem , we got it on our server running tho now on another os, is there a way getting the skins into the game like the spy one ? ( for others to view also )
